/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.ClientController;
import domen.Alat;
import domen.Inzenjer;
import domen.Lokacija;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofija
 */
public class MasinaForm extends javax.swing.JFrame {

    /**
     * Creates new form MasinaForm
     */
    Date datum1 = new Date();

    MasinaForm(MainForma aThis, boolean rootPaneCheckingEnabled, Inzenjer ulogovani) throws SQLException {
        initComponents();
        setLocationRelativeTo(null);

        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        txtDatum.setText(formatter.format(datum1));
        List<Lokacija> lokacije = ClientController.getInstanca().vratiSlobodneLokacije();

        for (Lokacija l : lokacije) {
            cmbLokacija.addItem(l);
        }

        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTip = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbLokacija = new javax.swing.JComboBox<>();
        txtNaziv = new javax.swing.JTextField();
        txtProizvodjac = new javax.swing.JTextField();
        txtRadniVek = new javax.swing.JTextField();
        txtGodina = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlati = new javax.swing.JTable();
        btnDodajAlat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDodati = new javax.swing.JTable();
        btnObrisiAlat = new javax.swing.JButton();
        btnSacuvajMasinu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv masine");

        jLabel2.setText("Proizvodjac");

        jLabel3.setText("Ocekivani radni vek");

        jLabel4.setText("Godina proizvodnje");

        jLabel5.setText("Datum pocetka");

        jLabel6.setText("Tip masine");

        cmbTip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "trafor", "skubler", "induktor", "bazer", "stator" }));
        cmbTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipActionPerformed(evt);
            }
        });

        jLabel7.setText("Lokacija");

        cmbLokacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLokacijaActionPerformed(evt);
            }
        });

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        tblAlati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAlati);

        btnDodajAlat.setText("Dodaj alat");
        btnDodajAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajAlatActionPerformed(evt);
            }
        });

        tblDodati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDodati);

        btnObrisiAlat.setText("Obrisi alat");
        btnObrisiAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiAlatActionPerformed(evt);
            }
        });

        btnSacuvajMasinu.setText("Sacuvaj masinu");
        btnSacuvajMasinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajMasinuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNaziv)
                                    .addComponent(txtProizvodjac)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbTip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbLokacija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtRadniVek)
                                    .addComponent(txtGodina)
                                    .addComponent(txtDatum)))
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDodajAlat)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnObrisiAlat)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSacuvajMasinu)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRadniVek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbTip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDodajAlat)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnObrisiAlat)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvajMasinu))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipActionPerformed

    private void cmbLokacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLokacijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLokacijaActionPerformed

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void btnSacuvajMasinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajMasinuActionPerformed
        try {
            String naziv = txtNaziv.getText();
            String proizvodjac = txtProizvodjac.getText();

            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");

            int radniVek;
            if (!txtRadniVek.equals("")) {
                radniVek = Integer.parseInt(txtRadniVek.getText());
            } else {
                radniVek = -1;
            }

            int godinaProizvodnje;
            if (!txtGodina.equals("")) {
                godinaProizvodnje = Integer.parseInt(txtGodina.getText());
            } else {
                godinaProizvodnje = -1;
            }

            Date datum;

            if (txtDatum != null) {
                datum = formatter.parse(txtDatum.getText());
            } else {
                datum = new Date(0);
            }

            String tip = (String) cmbTip.getSelectedItem();
            Lokacija lokacija = (Lokacija) cmbLokacija.getSelectedItem();

            if (naziv.equals("") || proizvodjac.equals("") || godinaProizvodnje < 1900 || godinaProizvodnje > 2023 || radniVek <= 0
                    || datum.after(datum1)) {
                JOptionPane.showMessageDialog(this, "Niste ispravno popunili podatke");
            }
        } catch (Exception ex) {
            Logger.getLogger(MasinaForm.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnSacuvajMasinuActionPerformed

    private void btnDodajAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajAlatActionPerformed

        try {
            int[] obelezeni = tblAlati.getSelectedRows();

            List<Alat> alati = ClientController.getInstanca().vratiListuObelezenihAlata(obelezeni);
            if (tblDodati.getRowCount() == 0) {

                TableModelAlati tb = new TableModelAlati(alati);
                tblDodati.setModel(tb);
            } else {

                for (int i = 0; i < tblDodati.getRowCount(); i++) {

                    int sifra = obelezeni[i] + 1;
                    String naziv = (String) tblDodati.getValueAt(i, 0);
                    int stanje = (int) tblDodati.getValueAt(i, 1);

                    Alat a = new Alat(sifra, naziv, stanje);
                    if(!alati.contains(a)) alati.add(a);
                }

                TableModelAlati tb = new TableModelAlati(alati);
                tblDodati.setModel(tb);
            }
            
            List<Alat> alati2 = ClientController.getInstanca().vratiListuAlata();
            TableModelAlati tb1= new TableModelAlati(alati2);
            tblAlati.setModel(tb1);
           
            

        } catch (SQLException ex) {
            Logger.getLogger(MasinaForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }


    }//GEN-LAST:event_btnDodajAlatActionPerformed

    private void btnObrisiAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiAlatActionPerformed
        
         

    }//GEN-LAST:event_btnObrisiAlatActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajAlat;
    private javax.swing.JButton btnObrisiAlat;
    private javax.swing.JButton btnSacuvajMasinu;
    private javax.swing.JComboBox<Object> cmbLokacija;
    private javax.swing.JComboBox<String> cmbTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAlati;
    private javax.swing.JTable tblDodati;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtProizvodjac;
    private javax.swing.JTextField txtRadniVek;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() throws SQLException {

        List<Alat> alati = ClientController.getInstanca().vratiListuAlata();
        TableModelAlati tb = new TableModelAlati(alati);
        tblAlati.setModel(tb);
        List<Alat> alati2 = new LinkedList<>();
        TableModelAlati tb2 = new TableModelAlati(alati2);
        tblDodati.setModel(tb2);
    }
}
